apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    run: email-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: email-service