apiVersion: v1
kind: Service
metadata:
  name: subscriber-queue-service
  labels:
    app: subscriber-queue
spec:
  type: NodePort
  ports:
    - port: 9092
      protocol: TCP
  selector:
    app: subscriber-queue
