apiVersion: v1
kind: Service
metadata:
  name: newsletter-db-service
  labels:
    app: newsletter-db
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: newsletter-db