apiVersion: v1
kind: Service
metadata:
  name: newsletter-service
  labels:
    run: newsletter-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: newsletter-service
